version: '3.8'
services:
  app:
    container_name: springboot_security_app
    image: springboot_security
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db_postgresql
  db_postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring_security_db